name = "ACEbase"
uuid = "14bae519-eb20-449c-a949-9c58ed33163e"
authors = ["Christoph Ortner <c.ortner@warwick.ac.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
